dist: trusty

language: php
php:
  - nightly

before_install:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpcs trans.php -n
  - vendor/bin/phpcs trans.php --standard=PHPCompatibility --runtime-set testVersion 4.0-
  - composer validate