dist: trusty

language: php
php:
  - nightly

before_script:
  - composer install --dev

script:
  - vendor/bin/phpcs trans.php --standard=PHPCompatibility --runtime-set testVersion 5.2-5.6
  - vendor/bin/phpcs trans.php --standard=PHPCompatibility --runtime-set testVersion 7.0-